name: StarWars.Node.Api Publish Workflow

on:
  push:
    branches: [ dev ]

permissions:
  packages: write

jobs:
  publish-starwars-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository...
        uses: actions/checkout@v4
      - name: Set up Docker Environment...
        uses: docker/setup-buildx-action@v3
      - name: Logging into Docker Registry...
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image...
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ghcr.io/bashfulbandit/starwars.node.api:latest,ghcr.io/bashfulbandit/starwars.node.api:1.0.1
